backend:
  name: github
  repo: thangchidoan/the-devigner-blog.github.io
  branch: master
  auth_endpoint: api/auth

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "pages"
    label: "Pages"
    files:
      - file: "about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
